# Generated by Django 3.2.3 on 2021-06-09 19:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210607_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
