# Generated by Django 3.2.3 on 2021-06-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_email'),
        ('api', '0015_alter_post_location'),
    ]

    operations = [
    ]
